package <%= appPackage %>.<%= packageName %>;

import android.os.Bundle
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import androidx.fragment.app.Fragment
import androidx.lifecycle.ViewModelProviders
import <%= appPackage %>.R
import <%= appPackage %>.ui.main.home.viewmodel.HomeViewModel

/**
 * Generated by generator-android-template
 */
class <%= name %> : Fragment() {
    private lateinit var viewModel: <%= name %>ViewModel

    override fun onCreateView(
            inflater: LayoutInflater,
            container: ViewGroup?,
            savedInstanceState: Bundle?
    ): View? {
        viewModel =
                ViewModelProviders.of(this).get(<%= name %>ViewModel::class.java)
        val root = inflater.inflate(R.layout.<%= layoutName %>, container, false)

        return root
    }
}
